### ISSUE TITLE
Eth Wire Protocol

### ISSUE THREAD

**Issue by germsvel** [mana-ethereum/mana#167]
We are currently handling the encrypted handshake and deriving secrets needed to frame the rest of the messages. 

Issue #166 will handle the DEVp2p handshake (and other messages). Once that handshake is successful, we can handle subprotocols. 

The main subprotocol is the Ethereum Wire Protocol (https://github.com/ethereum/wiki/wiki/Ethereum-Wire-Protocol). We should handle this first (both v62 and v63), and then deal with Whisper (issue #105) and Swarm (issue #104) later.

**Comment by masonforest** [comment]
Thanks for writing these! It's nice to have a better idea of where we are and where we are going.

I'd say implementing Whisper and Swarm should be postponed until other functionality is implemented because as far as I can tell they aren't part of the core protocol.

@igorbarinov you mentioned Whisper in Cincinnati. Does POA  require the Whisper protocol?

Swarm seems like a separate project all together. I don't see any reference to it in Parity.

It's too bad so much of this is up in the air: part of the nature of decentralization I guess.

**Comment by germsvel** [comment]
Yeah, from my point of view (which is still limited) I think we can defer Whisper and Swarm until much later. I just mentioned them in this issue because I knew we had issues for them, and I know they're mentioned around.

**Comment by masonforest** [comment]
cool, yeah good to have them on the Radar 👍

**Comment by hayesgm** [comment]
This has been completed.
